# -*- coding: utf-8 -*-
"""
Camada PROFUNDA dos 20 selos — material de estudo do Leo.

Extraido do telegram_kin_bot.py original em 03/09/2026, sem perda.
Esta camada NAO vai para a mensagem publica: e a aula diaria do /estudo.
Para o texto acessivel de grupo, ver ACESSIVEL em textos.py.
"""

PROFUNDO = {
    1: {
        'arquetipo': 'A Força Primordial / Mãe Cósmica',
        'descricao': 'Útero da criação, confiança primordial, nutrição do ser e resgate da memória ancestral',
        'corpo': '🟥 CORPO FÍSICO — Ancoragem Biológica, Nutrição Celular e Sistema Nervoso',
        'luz': 'Capacidade de gerar novos projetos, acolher incondicionalmente e confiar no fluxo da vida. Hoje é dia de INICIAR com confiança primordial.',
        'sombra': 'Sentimento crônico de desamparo, carência afetiva e desconfiança na existência. Vigie o controle por medo de abandono.',
        'chave': 'Você é nutrido pela própria existência. Confie no fluxo e permita-se receber.',
        'somat_contracao': 'Ativação de desamparo no sistema simpático: nó no estômago, sensação de vazio visceral ou compulsão por comer rápido sem mastigar.',
        'somat_expansao': 'Segurança biológica de base (vagal ventral): diafragma solto, calor no baixo ventre e sensação de estar seguro na própria pele.',
        'somat_higiene': 'Coma comida viva e densa. Beba água morna. Aterre a planta dos pés no chão e faça 5 minutos de respiração abdominal lenta.',
        'dir_trabalho': 'Plante a semente de algo novo com fé e coragem. Escreva a intenção central do seu próximo projeto em 1 frase clara.',
        'dir_relacoes': 'Pratique acolhimento. Ofereça presença a quem precisa ser ouvido sem julgamento. Prepare um alimento com afeto.',
        'auto_investigacao': 'Onde eu ainda sinto que preciso lutar sozinho para merecer cuidado? O que acontece no meu corpo quando eu confio que a vida me sustenta?',
        'guia_msg': 'O Farol Guia aponta para a nutrição original: pare de buscar validação fora e cuide da sua base biológica e emocional antes de qualquer movimento.',
        'analogo_msg': 'O Aliado de Apoio entrega vitalidade telúrica: garante calma nas vísceras e estabilidade corporal para sustentar o ritmo do dia.',
        'antipoda_msg': 'O Mestre do Desafio provoca a dor da carência ou a sensação de abandono: o treino de hoje é ser seu próprio refúgio e parar de mendigar afeto.',
        'oculto_msg': 'O Tesouro Oculto desperta a memória de que a vida sempre te sustentou nas travessias mais difíceis, liberando a paz de soltar o controle.',
        'quinta_msg': 'A Quinta Força sintetiza a Força Primordial: o poder soberano de gestar, acolher e alimentar a si mesmo e aos seus com dignidade.',
    },
    2: {
        'arquetipo': 'O Sumo Sacerdote / Sopro Divino',
        'descricao': 'Transmissão da verdade, palavra consciente, respiração vital (Prana) e escuta do espírito',
        'corpo': '⬜ CORPO MENTAL — Clareza Verbal, Discernimento e Purificação de Diálogos Internos',
        'luz': 'Clareza verbal, capacidade de inspirar com palavras e canal aberto para mensagens sutis. Hoje é dia de FALAR SUA VERDADE com amor.',
        'sombra': 'Falatório superficial, manipulação verbal ou medo de se expressar. Vigie palavras jogadas sem consciência.',
        'chave': 'A palavra é sopro divino. Antes de falar, respire. Antes de reagir, escute.',
        'somat_contracao': 'Contração laríngea e aperto no peito: sensação de garganta travada por engolir a própria verdade ou hiperventilação superficial.',
        'somat_expansao': 'Canal aéreo desobstruído: respiração ampla que chega aos pulmões profundos, voz ressonante e maxilar completamente destravado.',
        'somat_higiene': 'Pratique 5 minutos de respiração 4-7-8 (inspira em 4, segura em 7, solta em 8). Solte o ar com som de alívio.',
        'dir_trabalho': 'Comunique com clareza. Escreva a mensagem, grave o áudio, faça a reunião. A palavra consciente move montanhas.',
        'dir_relacoes': 'Diga o que precisa ser dito com firmeza e doçura. Ouça sem preparar resposta. A escuta atenta é a forma mais alta do Vento.',
        'auto_investigacao': 'Qual verdade eu estou engolindo por covardia ou conveniência? O que meu silêncio complacente está custando para a minha paz?',
        'guia_msg': 'O Farol Guia convoca você a alinhar a fala ao Espírito: não gaste palavras à toa e fale apenas aquilo que edifica e liberta.',
        'analogo_msg': 'O Aliado de Apoio abre canais de diálogo e sintonia fina, tornando sua expressão magnética, fluida e compreendida por todos.',
        'antipoda_msg': 'O Mestre do Desafio traz tagarelice mental e o medo do julgamento: o treino de hoje é domar a mente e falar com coragem cirúrgica.',
        'oculto_msg': 'O Tesouro Oculto é o sopro vital silencioso que restaura sua clareza instantaneamente quando você para e respira com presença.',
        'quinta_msg': 'A Quinta Força ativa o Mensageiro Cósmico: a capacidade de traduzir visões profundas em linguagem simples, poética e transformadora.',
    },
    3: {
        'arquetipo': 'O Sonhador Místico / Guardião do Silêncio',
        'descricao': 'Quietude fértil, intuição profunda, visão dos sonhos lúcidos e matriz da abundância invisível',
        'corpo': '🟦 CORPO EMOCIONAL — Intuição Profunda, Inconsciente, Sombra e Matriz dos Sonhos',
        'luz': 'Intuição aguçada, conexão com o subconsciente e capacidade de materializar sonhos. Hoje é dia de CONFIAR NA INTUIÇÃO silenciosa.',
        'sombra': 'Medo do escuro interior, sensação de escassez, isolamento depressivo e fuga da própria sombra.',
        'chave': 'A verdadeira abundância mora no invisível antes de se materializar. Confie no vazio fértil.',
        'somat_contracao': 'Sensação de peso ocular, aperto no plexo por medo de escassez ou insônia agitada por pensamentos ruminantes.',
        'somat_expansao': 'Sensação de recolhimento acolhedor: desaceleração profunda dos batimentos cardíacos, relaxamento ocular e sono reparador.',
        'somat_higiene': 'Desligue todas as telas 1 hora antes de dormir. Fique na penumbra. Coloque uma música suave e deixe o subconsciente decantar.',
        'dir_trabalho': 'Silêncio criativo. Não force decisões no atropelo. Deixe as ideias germinarem. A solução virá da intuição.',
        'dir_relacoes': 'Fiquem em silêncio juntos — sem celular, sem cobranças. Deixem o campo harmonizar sozinho na presença.',
        'auto_investigacao': 'Qual medo na minha sombra ainda dita minhas decisões por escassez? O que é a verdadeira abundância para mim?',
        'guia_msg': 'O Farol Guia direciona você a buscar as respostas na quietude interior: a lógica do mundo não resolve o que só a intuição decifra.',
        'analogo_msg': 'O Aliado de Apoio traz sonhos reveladores e a certeza visceral de que a abundância já está operando nos bastidores invisíveis.',
        'antipoda_msg': 'O Mestre do Desafio ativa o pavor da falta e do escuro: o treino de hoje é olhar para a própria sombra sem desespero e acolhê-la.',
        'oculto_msg': 'O Tesouro Oculto é a visão noturna da alma: enxergar saídas luminosas exatamente onde a mente racional só via beco sem saída.',
        'quinta_msg': 'A Quinta Força ativa o Místico Lúcido: o poder de sonhar a realidade com tanta convicção que o mundo material se alinha à visão.',
    },
    4: {
        'arquetipo': 'O Inocente / Visionário do Alvo',
        'descricao': 'Potencial latente, precisão do foco, respeito aos ciclos orgânicos e paciência para germinar',
        'corpo': '🟨 CORPO ESPIRITUAL — Foco Cósmico, Potencial Genético e Paciência Orgânica',
        'luz': 'Paciência, determinação, foco cirúrgico e capacidade de fazer florescer talentos ocultos. Hoje é dia de PLANTAR COM PRECISÃO.',
        'sombra': 'Rigidez perfeccionista, medo de errar e hesitação em germinar. Vigie a procrastinação disfarçada de perfeccionismo.',
        'chave': 'A semente não tem pressa. Ela confia no tempo. Plante com fé e solte o controle do resultado.',
        'somat_contracao': 'Tensão muscular nas têmporas e rigidez na mandíbula por hiperfoco ansioso e medo de errar a execução.',
        'somat_expansao': 'Tônus de concentração serena: coluna ereta sem rigidez, respiração ritmada e presença focada em uma única ação de cada vez.',
        'somat_higiene': 'Elimine todas as abas abertas e notificações. Beba água fresca em goles lentos para hidratar as células.',
        'dir_trabalho': 'Foco absoluto em 1 única tarefa de alto valor. Nada de multitarefa dispersa. Plante e cuide com atenção total.',
        'dir_relacoes': 'Reconheça o potencial latente no outro. Elogie com especificidade algo que a pessoa ainda não vê em si mesma.',
        'auto_investigacao': 'Qual semente eu plantei mas vivo desenterrando por ansiedade e desconfiança? O que eu preciso deixar maturar em silêncio?',
        'guia_msg': 'O Farol Guia aponta para a seleção do essencial: corte os galhos secos da rotina e direcione toda a sua energia para o alvo prioritário.',
        'analogo_msg': 'O Aliado de Apoio entrega paciência orgânica: sustenta a disciplina diária sem o desgaste do perfeccionismo doentio.',
        'antipoda_msg': 'O Mestre do Desafio dispara a pressa e a autocrítica paralisante: o treino de hoje é dar o passo imperfeito em vez de esperar o cenário ideal.',
        'oculto_msg': 'O Tesouro Oculto desperta talentos adormecidos no seu DNA: recursos que você nem lembrava que tinha desabrocham sob pressão.',
        'quinta_msg': 'A Quinta Força ativa o Mestre do Alvo: a mente cirúrgica que reconhece o momento exato de germinar e manifestar resultados sólidos.',
    },
    5: {
        'arquetipo': 'O Iniciado Serpente / Mestre da Kundalini',
        'descricao': 'Inteligência visceral do corpo físico, sexualidade sagrada, regeneração celular e vigor vital',
        'corpo': '🟥 CORPO FÍSICO — Kundalini, Sistema Nervoso Autônomo, Descarga Somática e Vigor',
        'luz': 'Vigor físico explosivo, intuição corporal precisa, magnetismo natural e recuperação rápida. Hoje é dia de HONRAR O CORPO.',
        'sombra': 'Apego a instintos de sobrevivência, reatividade cega ou apatia física. Vigie a impulsividade defensiva.',
        'chave': 'O corpo é o seu templo e o seu primeiro oráculo. Escute a sabedoria visceral antes de racionalizar.',
        'somat_contracao': 'Reatividade simpática de luta/fuga: contração da fáscia lombar, ombros encolhidos e pulso acelerado por alerta de perigo imaginário.',
        'somat_expansao': 'Fluidez neuromuscular: pelve relaxada, calor distribuído nos membros, vitalidade desperta e sensação de prontidão sem tensão.',
        'somat_higiene': 'Treino de força, corrida ou caminhada rápida para queimar o cortisol. Depois, banho quente alongando a cadeia posterior.',
        'dir_trabalho': 'Ação física e energia alta. Use a vitalidade para tarefas que exigem presença corporal, vigor e entrega intensa.',
        'dir_relacoes': 'Respeite o espaço visceral do outro. Toque com afeto. A intimidade hoje pede autenticidade e presença sincera.',
        'auto_investigacao': 'O que o meu corpo está me dizendo através das minhas contrações musculares? Onde eu ignorei meus limites biológicos recentemente?',
        'guia_msg': 'O Farol Guia convoca você a confiar na resposta visceral do corpo: se o estômago contrai, recue; se o peito expande, avance.',
        'analogo_msg': 'O Aliado de Apoio injeta vitalidade biológica e magnetismo pessoal para você trabalhar e se posicionar sem fadiga.',
        'antipoda_msg': 'O Mestre do Desafio ativa a reatividade irracional: o treino de hoje é não morder a isca de provocações e respirar antes de reagir.',
        'oculto_msg': 'O Tesouro Oculto é o poder de trocar de pele: regenerar a saúde e o ânimo após fases de esgotamento com velocidade surpreendente.',
        'quinta_msg': 'A Quinta Força ativa o Mestre da Kundalini: a união sagrada entre a inteligência dos instintos terrestres e a lucidez espiritual.',
    },
    6: {
        'arquetipo': 'O Hierofante / Diplomata Cósmico',
        'descricao': 'Desapego consciente, encerramento sagrado de ciclos, transcendência e conexão entre mundos',
        'corpo': '⬜ CORPO MENTAL — Desapego Lúcido, Fim de Projeções do Ego e Luto Sagrado',
        'luz': 'Facilidade para perdoar e soltar o passado, serenidade diante de finais e habilidade diplomática. Hoje é dia de SOLTAR com paz.',
        'sombra': 'Apego possessivo, medo da perda e teimosia em manter o que já morreu. Vigie o controle obsessivo.',
        'chave': 'Toda morte é uma ponte para um renascimento. Solte o que já cumpriu sua função com gratidão.',
        'somat_contracao': 'Sensação de aperto no peito e peso nas costas por carregar fardos de relações ou projetos do passado que já terminaram.',
        'somat_expansao': 'Leveza profunda no tronco: expiração completa com sensação de esvaziamento e paz com os desfechos da vida.',
        'somat_higiene': 'Limpeza do espaço físico: jogue fora papéis velhos, doe o que não usa e tome um banho com intenção consciente de descarrego.',
        'dir_trabalho': 'Encerre ciclos e limpe a mesa. Delete arquivos inúteis, cancele compromissos drenantes e finalize pendências.',
        'dir_relacoes': 'Perdoe uma mágoa antiga em silêncio. Solte a expectativa de que o outro mude. Aceite o presente como ele é.',
        'auto_investigacao': 'Qual ciclo, apego ou crença antiga já morreu e eu continuo tentando manter vivo por medo do vazio? O que me impede de soltar isso?',
        'guia_msg': 'O Farol Guia aponta para a elegância de soltar: perdoe, feche portas desgastadas e abra caminho para que novas pontes surjam.',
        'analogo_msg': 'O Aliado de Apoio traz diplomacia e poder de conciliação, permitindo acordos justos e transições de ciclo sem conflito.',
        'antipoda_msg': 'O Mestre do Desafio cutuca o medo da perda e a carência de controle: o treino de hoje é abrir as mãos e confiar no novo ciclo.',
        'oculto_msg': 'O Tesouro Oculto é a capacidade de enxergar oportunidades de ouro exatamente onde a maioria só vê crise, perda e fim de linha.',
        'quinta_msg': 'A Quinta Força ativa o Construtor de Pontes: a sabedoria de unir realidades diferentes e transitar com leveza entre o terreno e o sutil.',
    },
    7: {
        'arquetipo': 'O Avatar / Construtor da Realidade',
        'descricao': 'Cura pelas mãos, inteligência prática executiva, conclusão de tarefas e ancoragem da obra na matéria',
        'corpo': '🟦 CORPO EMOCIONAL — Cura pelas Mãos, Conclusão de Feridas Abertas e Auto-acolhimento',
        'luz': 'Eficiência, dom de cura pelas mãos, concretização de projetos e resolução prática. Hoje é dia de CONCLUIR e CONSTRUIR.',
        'sombra': 'Complexo de salvador, perfeccionismo e burnout por carregar o fardo dos outros. Vigie a compulsão de resolver tudo.',
        'chave': 'Você cura o mundo curando a si mesmo primeiro. Termine o que começou e descanse sem culpa.',
        'somat_contracao': 'Tensão aguda nos punhos, antebraços e trapézios por sobrecarga de trabalho e postura de "carregar tudo nas costas".',
        'somat_expansao': 'Mãos quentes, palmas relaxadas e respiração tranquila de dever cumprido ao fechar um ciclo aberto de entrega.',
        'somat_higiene': 'Lave as mãos com água fria e sabão esfregando com intenção de descarrego. Alongue punhos e dedos.',
        'dir_trabalho': 'Conclua tarefas. Feche processos abertos, entregue o que está pendente, coloque a mão na massa com método e finalização.',
        'dir_relacoes': 'Ofereça ajuda prática — não apenas conselhos teóricos. Cozinhe, organize, conserte algo. A Mão serve pela ação.',
        'auto_investigacao': 'Onde eu estou me sobrecarregando tentando salvar ou consertar a vida dos outros? Qual tarefa aberta está roubando a minha paz?',
        'guia_msg': 'O Farol Guia direciona você a finalizar pendências: termine o que começou para estancar o vazamento de energia mental.',
        'analogo_msg': 'O Aliado de Apoio entrega inteligência técnica e destreza manual para descomplicar problemas difíceis com soluções simples.',
        'antipoda_msg': 'O Mestre do Desafio ativa o complexo de salvador e a ilusão de que só você sabe fazer: o treino de hoje é delegar e cuidar de si.',
        'oculto_msg': 'O Tesouro Oculto é a energia curativa que emana da sua presença quando você atua com intenção pura e método organizado.',
        'quinta_msg': 'A Quinta Força ativa o Realizador Sagrado: a capacidade de transformar conhecimento teórico em obras sólidas e curativas na matéria.',
    },
    8: {
        'arquetipo': 'O Artista Cósmico / Harmonizador',
        'descricao': 'Proporção áurea, harmonia estética, elegância nas atitudes e brilho pessoal sem arrogância',
        'corpo': '🟨 CORPO ESPIRITUAL — Harmonia Áurica, Proporção Áurea e Alinhamento Estético',
        'luz': 'Senso estético refinado, capacidade de harmonizar ambientes e relações, brilho autêntico. Hoje é dia de EMBELEZAR.',
        'sombra': 'Vaidade excessiva, julgamento estético e superficialidade disfarçada de refinamento. Vigie a arrogância sutil.',
        'chave': 'A verdadeira elegância é a harmonia entre o que você sente e o que você expressa.',
        'somat_contracao': 'Rigidez na expressão facial e autocrítica ácida diante de imperfeições no espelho ou no ambiente.',
        'somat_expansao': 'Harmonia áurica: sensação de leveza estética no peito, postura ereta e fluidez suave nos movimentos corporais.',
        'somat_higiene': 'Vista uma roupa que honre seu valor. Arrume o seu ambiente de trabalho. Coloque beleza no que seus olhos enxergam.',
        'dir_trabalho': 'Refine a forma. Melhore o design, a apresentação visual e a estética do seu trabalho. A beleza atrai respeito.',
        'dir_relacoes': 'Elogie a beleza no outro — uma virtude, um gesto, uma gentileza. A Estrela reconhece o brilho de quem está ao lado.',
        'auto_investigacao': 'Como posso trazer mais harmonia e beleza para a minha rotina sem me perder na armadilha do perfeccionismo e da vaidade?',
        'guia_msg': 'O Farol Guia aponta para a proporção áurea: equilibre as atitudes, transforme o atrito em harmonia e mantenha a elegância sob pressão.',
        'analogo_msg': 'O Aliado de Apoio traz charme, magnetismo e bom gosto natural, facilitando negociações e encantando quem ouve você.',
        'antipoda_msg': 'O Mestre do Desafio dispara a intolerância com o caos e a arrogância estética: o treino de hoje é amar a beleza crua da vida.',
        'oculto_msg': 'O Tesouro Oculto é o seu brilho autêntico e despretensioso: quando você é você mesmo sem tentar impressionar, sua presença ilumina.',
        'quinta_msg': 'A Quinta Força ativa o Artista Cósmico: a maestria de viver o Tempo como Arte, tornando cada ação e conversa uma obra harmônica.',
    },
    9: {
        'arquetipo': 'A Sacerdotisa da Água / Farol da Consciência',
        'descricao': 'Fluidez emocional, purificação de memórias, lembrança de quem você é e respeito às marés da vida',
        'corpo': '🟥 CORPO FÍSICO — Drenagem Linfática, Fluidez Celular e Liberação Emocional Somática',
        'luz': 'Fluidez emocional saudável, purificação de memórias tóxicas e lembrança de quem você é. Hoje é dia de PURIFICAR e FLUIR.',
        'sombra': 'Represamento emocional, rigidez diante de mudanças e vitimismo. Vigie a resistência ao fluxo natural.',
        'chave': 'Deixe a água correr. A emoção que flui purifica; a emoção represada adoece.',
        'somat_contracao': 'Retenção hídrica, nó na garganta por choro reprimido e peso no baixo ventre por apego a mágoas antigas.',
        'somat_expansao': 'Liberação das águas internas: alívio após o choro consciente, drenagem celular e sensação de frescor no corpo.',
        'somat_higiene': 'Beba 2 litros de água pura. Tome um banho demorado deixando a água cair no topo da cabeça descarregando tudo.',
        'dir_trabalho': 'Limpe a fila emocional. Resolva pendências que envolvem sentimentos engasgados. Responda com verdade e perdoe.',
        'dir_relacoes': 'Permita-se expressar vulnerabilidade. A vulnerabilidade autêntica é a ponte mais sólida entre dois corações.',
        'auto_investigacao': 'Qual emoção eu estou represando por orgulho ou medo de parecer vulnerável? O que acontece no meu corpo se eu simplesmente deixar fluir?',
        'guia_msg': 'O Farol Guia convoca você a purificar intenções e deixar as águas correrem: não segure o fluxo dos sentimentos nem force diques.',
        'analogo_msg': 'O Aliado de Apoio confere sensibilidade e compaixão natural para acolher os sentimentos alheios com respeito e empatia.',
        'antipoda_msg': 'O Mestre do Desafio ativa tempestades emocionais e vitimismo: o treino de hoje é ser o leito firme do rio por onde a água passa.',
        'oculto_msg': 'O Tesouro Oculto é a regeneração através da entrega: a capacidade de se purificar em 10 minutos de recolhimento sincero.',
        'quinta_msg': 'A Quinta Força ativa a Sacerdotisa da Água: a consciência que limpa resíduos do passado e sustenta a memória da verdade pura.',
    },
    10: {
        'arquetipo': 'O Compassivo / Guardião do Amor',
        'descricao': 'Amor sem cobranças, lealdade à própria essência e aos parceiros de jornada, abertura do chakra cardíaco',
        'corpo': '⬜ CORPO MENTAL — Superação de Julgamentos Punitivos e Pacificação da Mente Crítica',
        'luz': 'Amor incondicional genuíno, lealdade inabalável e capacidade de amar sem cobranças. Hoje é dia de ABRIR O CORAÇÃO.',
        'sombra': 'Carência afetiva, dependência emocional e lealdade cega a quem não merece. Vigie o medo de amar.',
        'chave': 'O amor verdadeiro não exige reciprocidade imediata. Ele existe porque você escolhe amar.',
        'somat_contracao': 'Sensação de armadura no peito, respiração curta no tórax e contração defensiva por medo de rejeição ou traição.',
        'somat_expansao': 'Calor radiante no centro do peito: batimentos cardíacos coerentes, sensação de pertencimento e acolhimento incondicional.',
        'somat_higiene': 'Coloque a palma da mão no centro do peito e respire fundo 7 vezes sentindo o calor e o ritmo do seu próprio coração.',
        'dir_trabalho': 'Sirva com o coração. Faça o trabalho com amor genuíno, não só por obrigação. A qualidade reflete o coração.',
        'dir_relacoes': 'Diga "eu te amo" olhando nos olhos. Pratique atos de afeto concretos: mensagens de carinho e escuta sem pressa.',
        'auto_investigacao': 'Onde eu estou cobrando amor e lealdade do outro em vez de ser a minha própria fonte de acolhimento e respeito próprio?',
        'guia_msg': 'O Farol Guia aponta para a lealdade incondicional aos seus valores e aos seus parceiros: sirva com o coração sem se trair.',
        'analogo_msg': 'O Aliado de Apoio abre portas através do companheirismo e da empatia, gerando confiança instantânea nos ambientes.',
        'antipoda_msg': 'O Mestre do Desafio ativa a carência e o medo do abandono: o treino de hoje é estabelecer limites dignos e amar sem dependência.',
        'oculto_msg': 'O Tesouro Oculto é a coragem mansa do perdão: restaurar pontes e dissolver ressentimentos com um simples abraço sincero.',
        'quinta_msg': 'A Quinta Força ativa o Guardião do Amor: a autoridade compassiva que pacifica conflitos e traz harmonia para o clã.',
    },
    11: {
        'arquetipo': 'O Mágico / Alquimista Brincalhão',
        'descricao': 'Desconstrução da rigidez pelo humor, criatividade genial, quebra de ilusões e leveza lúcida',
        'corpo': '🟦 CORPO EMOCIONAL — Criança Interior, Desmonte da Rigidez e Alquimia do Humor',
        'luz': 'Genialidade criativa, humor inteligente, capacidade de desconstruir o pesado com leveza. Hoje é dia de BRINCAR.',
        'sombra': 'Irresponsabilidade, sarcasmo destrutivo e fuga pela piada para não encarar a dor. Vigie a evasão.',
        'chave': 'O humor sagrado dissolve o medo. Ria de si mesmo com carinho e a ilusão perde o poder.',
        'somat_contracao': 'Mandíbula travada em sisudez rígida, testa franzida e sensação de peso insuportável por se levar a sério demais.',
        'somat_expansao': 'Soltura muscular espontânea: riso no ventre, olhos brilhantes e flexibilidade ágil nas articulações.',
        'somat_higiene': 'Pule, balance os braços soltos, faça caretas no espelho e ria de si mesmo. O movimento lúdico quebra a couraça muscular.',
        'dir_trabalho': 'Criatividade solta. Brainstorm sem censura, ideias ousadas, testes rápidos. O melhor trabalho nasce brincando.',
        'dir_relacoes': 'Riam juntos. Contem piadas, relembrem memórias leves, dancem na cozinha. A leveza cura mais que mil discursos.',
        'auto_investigacao': 'Onde eu estou me levando a sério demais e criando um drama desnecessário? Como a minha criança interior resolveria isso com leveza?',
        'guia_msg': 'O Farol Guia convoca você a desmontar a rigidez do ego: enxergue o jogo cósmico da vida e use a criatividade como chave mestra.',
        'analogo_msg': 'O Aliado de Apoio traz inventividade e quebra de padrões obsoletos, desarmando o peso de reuniões e processos engessados.',
        'antipoda_msg': 'O Mestre do Desafio dispara a solenidade doentia ou a ironia defensiva: o treino de hoje é usar o humor para libertar, nunca para ferir.',
        'oculto_msg': 'O Tesouro Oculto é o estalo de genialidade da criança: descobrir a solução exata para um problema enquanto você relaxa e brinca.',
        'quinta_msg': 'A Quinta Força ativa o Alquimista da Realidade: o mestre que desmascara ilusões sociais e devolve a magia e o encantamento ao cotidiano.',
    },
    12: {
        'arquetipo': 'O Sábio da Terra / Cálice Sagrado',
        'descricao': 'Responsabilidade pelas próprias escolhas, respeito ao livre-arbítrio alheio e sabedoria colhida na vivência',
        'corpo': '🟨 CORPO ESPIRITUAL — Autorresponsabilidade, Sabedoria Vivida e Saída do Vitimismo',
        'luz': 'Maturidade ética, sabedoria prática colhida na vivência e respeito genuíno ao livre-arbítrio. Hoje é dia de ESCOLHER COM SABEDORIA.',
        'sombra': 'Arrogância intelectual, manipulação das escolhas alheias ou vitimismo. Vigie a terceirização de culpa.',
        'chave': 'Cada escolha que você faz é uma oração viva. Escolha com consciência e arque com as consequências em paz.',
        'somat_contracao': 'Sensação de paralisia na tomada de decisão, peso na cabeça por excesso de racionalização e terceirização de culpa.',
        'somat_expansao': 'Espinha dorsal alinhada, presença centrada e sensação de soberania calma sobre os próprios passos e escolhas.',
        'somat_higiene': 'Sente-se com a coluna reta em uma cadeira firme. Sinta os ísquios apoiados. Respire fundo e tome a decisão pendente.',
        'dir_trabalho': 'Decisões estratégicas. Avalie com bom senso e tome a decisão adiada. O livre-arbítrio é o seu poder na matéria.',
        'dir_relacoes': 'Respeite o livre-arbítrio do outro. Não tente moldar ninguém. Ofereça a sua perspectiva e solte o controle.',
        'auto_investigacao': 'Qual decisão crucial eu continuo adiando e terceirizando para as circunstâncias? O que eu escolho assumir por inteiro, sem dividir a culpa?',
        'guia_msg': 'O Farol Guia aponta para a sabedoria das escolhas conscientes: assuma a rédea do seu destino e aja com ética irrepreensível.',
        'analogo_msg': 'O Aliado de Apoio confere bom senso e discernimento prático para guiar pessoas e projetos com maturidade e firmeza.',
        'antipoda_msg': 'O Mestre do Desafio cutuca a tentação de se fazer de vítima ou culpar terceiros: o treino de hoje é assumir a responsabilidade total.',
        'oculto_msg': 'O Tesouro Oculto é a sabedoria colhida nas cicatrizes antigas: seus erros passados se convertem na sua bússola mais precisa.',
        'quinta_msg': 'A Quinta Força ativa o Sábio da Terra: o ser humano que alcançou a maestria de viver em harmonia com sua verdade mais profunda.',
    },
    13: {
        'arquetipo': 'O Profeta / Peregrino das Estrelas',
        'descricao': 'Rompimento de limites e fronteiras, coragem de desbravar o desconhecido e travessia de limiares',
        'corpo': '🟥 CORPO FÍSICO — Exploração de Novos Ambientes, Quebra de Inércia e Aterramento',
        'luz': 'Coragem de explorar o desconhecido, espírito inovador e capacidade de romper limites autoimpostos. Hoje é dia de EXPANDIR.',
        'sombra': 'Inquietude crônica, fuga geográfica dos problemas e superficialidade. Vigie a dispersão.',
        'chave': 'O verdadeiro espaço a explorar está dentro de você. A maior aventura é a jornada interior ancorada no presente.',
        'somat_contracao': 'Inquietação nas pernas (síndrome das pernas inquietas), respiração superficial e ansiedade de querer estar em outro lugar.',
        'somat_expansao': 'Sensação de espaço interno ampliado: pulmões cheios, pés firmes e olhar aberto para novos horizontes sem medo.',
        'somat_higiene': 'Caminhe ao ar livre mudando de rota. Observe o céu e o horizonte por 10 minutos para expandir o campo visual.',
        'dir_trabalho': 'Explore possibilidades. Pesquise novas referências, estude novos temas, faça contatos fora da sua bolha.',
        'dir_relacoes': 'Surpreenda com algo inédito. Um convite diferente, um passeio novo, uma conversa sobre horizontes futuros.',
        'auto_investigacao': 'Qual fronteira ou medo imaginário está aprisionando o meu crescimento? O que há do outro lado desse limite se eu der o passo?',
        'guia_msg': 'O Farol Guia desafia você a romper barreiras conhecidas: pise no desconhecido com vigilância lúcida e coragem pioneira.',
        'analogo_msg': 'O Aliado de Apoio traz adaptabilidade e mente investigativa, facilitando a navegação em cenários inéditos e mutáveis.',
        'antipoda_msg': 'O Mestre do Desafio ativa a claustrofobia e a vontade de fugir das obrigações: o treino de hoje é habitar o presente antes de partir.',
        'oculto_msg': 'O Tesouro Oculto é a certeza visceral de que você tem proteção em qualquer travessia: seu centro espiritual é a sua casa.',
        'quinta_msg': 'A Quinta Força ativa o Guardião de Limiares: o pioneiro que abre caminhos onde não havia estrada e guia os outros com segurança.',
    },
    14: {
        'arquetipo': 'O Mago do Infinito / Xamã do Coração',
        'descricao': 'Magia da presença pura, silenciamento da mente racional, visão atemporal e receptividade sagrada',
        'corpo': '⬜ CORPO MENTAL — Silenciamento da Mente Racional, Presença Pura e Foco no Agora',
        'luz': 'Presença magnética que encanta sem esforço, clareza intuitiva e capacidade de habitar o Agora. Hoje é dia de SER PRESENÇA.',
        'sombra': 'Fuga para abstração etérea, manipulação e recusa de habitar a matéria. Vigie a procrastinação disfarçada.',
        'chave': 'A magia não mora no futuro nem no passado. Ela pulsa neste exato momento. Habite o Agora.',
        'somat_contracao': 'Dissociação corporal: sensação de estar "fora do corpo", cabeça fervendo de ideias e perda de contato com a matéria.',
        'somat_expansao': 'Presença pura ancorada: batimento cardíaco lento, olhar magnético sereno e relaxamento profundo no momento presente.',
        'somat_higiene': 'Feche os olhos por 10 minutos em silêncio absoluto. Apenas observe a respiração sem interferir. Sinta a pele.',
        'dir_trabalho': 'Presença pura. Faça menos tarefas, mas com atenção total. Uma de cada vez com o coração. A magia está no foco.',
        'dir_relacoes': 'Esteja 100% presente com quem está ao seu lado. Sem telas, sem pressa. A sua presença é o maior presente.',
        'auto_investigacao': 'Onde eu estou fugindo do momento presente com ansiedade do futuro ou culpa do passado? O que é real e sagrado AGORA?',
        'guia_msg': 'O Farol Guia convoca você a silenciar o ruído e agir a partir da presença pura: a verdadeira magia acontece sem força bruta.',
        'analogo_msg': 'O Aliado de Apoio permite captar nuances sutis e criar conexões magnéticas pela simples qualidade da sua escuta e presença.',
        'antipoda_msg': 'O Mestre do Desafio dispara a fuga para abstrações teóricas e a hesitação de agir: o treino de hoje é materializar no chão.',
        'oculto_msg': 'O Tesouro Oculto é o silêncio interior que transmuta o caos: fechar os olhos no olho do furacão e restaurar a ordem no campo.',
        'quinta_msg': 'A Quinta Força ativa o Mago do Infinito: a consciência atemporal que sabe que todo o poder de criação reside no eterno Agora.',
    },
    15: {
        'arquetipo': 'O Vidente Cósmico / Arquiteto Planetário',
        'descricao': 'Visão panorâmica de longo alcance, metavisão estratégica, criação pela mente superior e compaixão',
        'corpo': '🟦 CORPO EMOCIONAL — Metavisão das Dores, Quebra de Apego a Conflitos Locais e Criação',
        'luz': 'Visão de águia sobre a própria vida, capacidade estratégica e compaixão lúcida. Hoje é dia de VER DE CIMA.',
        'sombra': 'Frieza analítica, arrogância intelectual e distanciamento emocional. Vigie a desconexão do coração.',
        'chave': 'A visão sem compaixão é tirania. Veja o todo, mas nunca perca de vista o coração de cada detalhe.',
        'somat_contracao': 'Fadiga ocular intensa por telas, rigidez na base do crânio e distanciamento emocional gélido.',
        'somat_expansao': 'Visão periférica ampla: relaxamento dos globos oculares, mente lúcida e coração aberto para acolher o cenário.',
        'somat_higiene': 'Olhe para o ponto mais distante do horizonte por 5 minutos sem piscar com pressa. Descanse os olhos na luz natural.',
        'dir_trabalho': 'Planejamento estratégico. Suba o drone mental e olhe o projeto de cima. Trace o mapa dos próximos passos com clareza.',
        'dir_relacoes': 'Olhe as relações com metavisão — compreenda o contexto amplo de cada pessoa sem se prender a picuinhas.',
        'auto_investigacao': 'Se eu olhasse para os meus dilemas atuais daqui a 10 anos, o que pareceria pequeno demais para roubar a minha paz?',
        'guia_msg': 'O Farol Guia convoca você a subir o drone da consciência: tome decisões com visão estratégica de longo alcance aliada à compaixão.',
        'analogo_msg': 'O Aliado de Apoio garante clareza intelectual e criatividade refinada para desenhar soluções muito antes dos outros.',
        'antipoda_msg': 'O Mestre do Desafio dispara a frieza crítica e o pessimismo analítico: o treino de hoje é usar a mente para edificar e acolher.',
        'oculto_msg': 'O Tesouro Oculto é o poder de materializar visões: quando sua mente se alinha a um propósito nobre, os recursos aparecem.',
        'quinta_msg': 'A Quinta Força ativa o Vidente Planetário: a mente que enxerga o plano maior da evolução e ajuda a arquitetar novas realidades.',
    },
    16: {
        'arquetipo': 'O Descobridor / Guardião da Verdade',
        'descricao': 'Questionamento lúcido que não aceita dogmas, inteligência focada, coragem moral e integridade',
        'corpo': '🟨 CORPO ESPIRITUAL — Espada da Verdade, Desarme de Ilusões e Coragem Ética',
        'luz': 'Inteligência prática destemida, coragem de questionar e integridade ética inabalável. Hoje é dia de QUESTIONAR com coragem.',
        'sombra': 'Combatividade destrutiva, teimosia e beligerância disfarçada de justiça. Vigie a agressividade intelectual.',
        'chave': 'O verdadeiro guerreiro luta consigo mesmo primeiro. A maior batalha é a da autenticidade.',
        'somat_contracao': 'Tensão na armadura peitoral, punhos cerrados e postura combativa de quem espera ser atacado a qualquer instante.',
        'somat_expansao': 'Tônus de coragem mansa: peito aberto sem armaduras, olhar firme e sereno, e passos determinados sem agressividade.',
        'somat_higiene': 'Treino de alta intensidade (musculação ou corrida) para canalizar a energia marcial. Depois, relaxamento e respiração.',
        'dir_trabalho': 'Questionamento estratégico. Desafie pressupostos, questione processos obsoletos e pergunte "por quê?" até a raiz.',
        'dir_relacoes': 'Tenha conversas difíceis com amor. Fale com clareza e escute com honestidade, sem levantar a espada da defesa.',
        'auto_investigacao': 'Qual mentira conveniente eu estou contando para mim mesmo? Qual pergunta corajosa eu venho evitando me fazer?',
        'guia_msg': 'O Farol Guia aponta para a coragem moral: questione as convenções, defenda o que é justo e aja com integridade inegociável.',
        'analogo_msg': 'O Aliado de Apoio confere firmeza de caráter e inteligência tática para vencer resistências sem precisar gritar.',
        'antipoda_msg': 'O Mestre do Desafio ativa a beligerância cega e a desconfiança paranoica: o treino de hoje é abaixar o escudo e confiar na verdade.',
        'oculto_msg': 'O Tesouro Oculto é a força serena que desce do centro do peito: permanecer inabalável diante de ameaças e pressões externas.',
        'quinta_msg': 'A Quinta Força ativa o Guardião da Verdade: o investigador lúcido que dissipa a mentira e restabelece a ordem com firmeza.',
    },
    17: {
        'arquetipo': 'O Navegador Cósmico / Sismógrafo de Gaia',
        'descricao': 'Leitura dos sinais e sincronicidades, alinhamento com a ordem cósmica e aterramento profundo em Gaia',
        'corpo': '🟥 CORPO FÍSICO — Conexão com Gaia, Sincronização Biológica e Ritmo Natural',
        'luz': 'Leitura natural das sincronicidades, aterramento e conexão visceral com a Terra. Hoje é dia de LER OS SINAIS.',
        'sombra': 'Insensibilidade aos sinais, desconexão da natureza ou superstição obsessiva. Vigie a perda do bom senso.',
        'chave': 'A Terra fala para quem pisa descalço. Ouça com os pés, não com a mente ansiosa.',
        'somat_contracao': 'Tontura, mente aérea descolada da realidade e perda de estabilidade gravitacional nos pés.',
        'somat_expansao': 'Enraizamento telúrico: pés firmes no chão, coluna estável como uma montanha e sincronização com os ritmos da Terra.',
        'somat_higiene': 'Pise descalço na terra ou grama por 10 minutos. Sinta a gravidade puxando as tensões mentais para o centro da Terra.',
        'dir_trabalho': 'Alinhe-se com o fluxo. Observe os sinais do dia — convites, mensagens inesperadas, padrões. O rumo se revela.',
        'dir_relacoes': 'Pise na terra juntos. Um momento na natureza recalibra qualquer relação com a harmonia primordial da vida.',
        'auto_investigacao': 'Quais sincronicidades e sinais a vida colocou no meu caminho recentemente? O que eles estão apontando para o meu próximo passo?',
        'guia_msg': 'O Farol Guia direciona você a navegar pelos sinais sutis da vida: pare de remar contra a maré e sincronize seus passos com Gaia.',
        'analogo_msg': 'O Aliado de Apoio traz estabilidade geológica e paciência cósmica para construir alicerces inabaláveis na matéria.',
        'antipoda_msg': 'O Mestre do Desafio dispara a sobrecarga sensorial e o medo do futuro: o treino de hoje é fincar raízes e viver o ritmo do dia.',
        'oculto_msg': 'O Tesouro Oculto é a inteligência gravitacional da Terra: o magnetismo que reabastece seu corpo no momento em que você pisa no chão.',
        'quinta_msg': 'A Quinta Força ativa o Navegador Cósmico: a consciência que lê as correntes do tempo e sempre conduz com segurança ao destino certo.',
    },
    18: {
        'arquetipo': 'O Yogi / Lâmina da Verdade',
        'descricao': 'Verdade sem distorções do ego, clareza impecável, lâmina de corte de ilusões e ordem sagrada',
        'corpo': '⬜ CORPO MENTAL — Fim de Projeções do Ego, Autocrítica Consciente e Ordem Sagrada',
        'luz': 'Discernimento cristalino, capacidade de ver a verdade sem filtros e coragem de se enxergar. Hoje é dia de VER COM CLAREZA.',
        'sombra': 'Autocrítica paralisante, julgamento implacável e perfeccionismo cruel. Vigie a auto-flagelação.',
        'chave': 'O espelho não mente, mas também não julga. Olhe-se com compaixão impecável.',
        'somat_contracao': 'Contração aguda na nuca e ombros travados por julgamento impiedoso de si mesmo e autocrítica corrosiva.',
        'somat_expansao': 'Claridade mental translúcida: relaxamento facial total, respiração límpida e cessação de todo diálogo interno acusador.',
        'somat_higiene': 'Olhe nos seus próprios olhos no espelho por 3 minutos em silêncio absoluto. Respire fundo e diga: "Eu acolho quem eu sou hoje."',
        'dir_trabalho': 'Audite com verdade. Revise números, processos e entregas com honestidade cirúrgica. Elimine o que não funciona.',
        'dir_relacoes': 'Perceba o que te irrita no outro: muitas vezes é o espelho do que precisa ser acolhido em você. Auto-observação.',
        'auto_investigacao': 'O que eu estou projetando com tanta raiva ou frustração nos outros que é, na verdade, um reflexo do que recuso acolher em mim?',
        'guia_msg': 'O Farol Guia aponta para a ordem sagrada: use a lâmina do discernimento para cortar ilusões e veja as coisas como realmente são.',
        'analogo_msg': 'O Aliado de Apoio entrega sobriedade e justiça impecável para avaliar situações sem se deixar contaminar por reações emocionais.',
        'antipoda_msg': 'O Mestre do Desafio ativa a autocrítica impiedosa e o tribunal do ego: o treino de hoje é usar a verdade para curar, nunca para punir.',
        'oculto_msg': 'O Tesouro Oculto é a meditação do ponto zero: o silêncio absoluto que reina no centro do seu ser além de todas as ilusões.',
        'quinta_msg': 'A Quinta Força ativa o Mestre da Ordem Sagrada: a mente límpida que reflete a verdade divina e dissipa qualquer engano pela presença.',
    },
    19: {
        'arquetipo': 'O Mudador de Mundos / Mestre do Raio',
        'descricao': 'Autotransmutação radical, energia pura de renovação, quebra de estagnação e catarse construtiva',
        'corpo': '🟦 CORPO EMOCIONAL — Catarse Construtiva, Autotransmutação e Quebra de Estagnação',
        'luz': 'Energia explosiva de renovação, capacidade de catalisar mudanças profundas em si e no ambiente. Hoje é dia de MUDAR.',
        'sombra': 'Caos descontrolado, mudança compulsiva e drama destrutivo. Vigie o vício na instabilidade.',
        'chave': 'A tormenta limpa o céu. Deixe o raio agir e confie que depois vem a calmaria restauradora.',
        'somat_contracao': 'Voltagem elétrica represada no corpo: tremores sutis, agitação motora e sensação de que vai explodir de pressão.',
        'somat_expansao': 'Catarse descarregada: sensação de purificação eletromagnética, corpo leve após a tempestade e serenidade no centro do peito.',
        'somat_higiene': 'Treino de força explosivo ou dança vigorosa para descarregar a alta voltagem. Depois, banho gelado ou alternado.',
        'dir_trabalho': 'Catalise mudanças. Quebre velhos padrões, mude fluxos, reestruture o que está estagnado. Revolução construtiva.',
        'dir_relacoes': 'Permita que as relações evoluam. Não tente manter o outro preso a versões antigas. Deixe a renovação agir.',
        'auto_investigacao': 'Qual estrutura obsoleta na minha vida precisa ser destruída pelo raio da transformação para que a minha verdade possa respirar?',
        'guia_msg': 'O Farol Guia convoca você a autogerar energia e quebrar a casca velha: não tema a crise, ela é o motor do seu próximo nível.',
        'analogo_msg': 'O Aliado de Apoio acelera transformações que levariam anos, destravando a evolução com altíssima potência transformadora.',
        'antipoda_msg': 'O Mestre do Desafio cutuca o apego a dramas e o medo do caos: o treino de hoje é ser o olho sereno no centro do furacão.',
        'oculto_msg': 'O Tesouro Oculto é a capacidade de renascer das cinzas com o dobro de vigor e clareza após as tempestades mais duras.',
        'quinta_msg': 'A Quinta Força ativa o Mudador de Mundos: o catalisador que transforma estagnação em movimento vivo por onde quer que passe.',
    },
    20: {
        'arquetipo': 'O Iluminado / Consciência Crística',
        'descricao': 'Amor incondicional, iluminação da verdade, vida plena, sabedoria viva e autoridade benevolente',
        'corpo': '🟨 CORPO ESPIRITUAL — Selagem Áurica, Maestria Solar e Amor Incondicional Pleno',
        'luz': 'Iluminação interior, autoridade benevolente e capacidade de irradiar amor universal. Hoje é dia de BRILHAR com autenticidade.',
        'sombra': 'Megalomania espiritual, complexo de guru e arrogância de quem se acha superior. Vigie o ego espiritual.',
        'chave': 'O sol não precisa provar que brilha. Ele apenas é. Brilhe sem precisar de plateia.',
        'somat_contracao': 'Tensão no plexo solar por necessidade de validação externa ou frustração por não ser reconhecido e aplaudido.',
        'somat_expansao': 'Calor solar irradiando do coração para todo o corpo: respiração plena, olhar caloroso e serenidade soberana.',
        'somat_higiene': 'Tome 15 minutos de sol da manhã na pele. Sinta a luz ativando a produção de vitamina D e a vitalidade mitocondrial.',
        'dir_trabalho': 'Irradie maestria. Compartilhe o seu melhor trabalho, ensine, lidere com generosidade. Sua presença clareia o caminho.',
        'dir_relacoes': 'Seja a luz acolhedora do ambiente sem ofuscar ninguém. Pratique generosidade silenciosa e amor sem cobranças.',
        'auto_investigacao': 'Como eu compartilho a minha sabedoria por pura generosidade com a vida, sem depender de aplausos ou validação?',
        'guia_msg': 'O Farol Guia aponta para a consciência da unidade: viva com nobreza e irradie clareza e calor para todos sem distinção.',
        'analogo_msg': 'O Aliado de Apoio entrega autoridade benevolente e presença acolhedora, inspirando confiança e respeito espontâneo.',
        'antipoda_msg': 'O Mestre do Desafio cutuca o orgulho do ego e o complexo de superioridade: o treino de hoje é brilhar com humildade sagrada.',
        'oculto_msg': 'O Tesouro Oculto é a chama crística que nunca se apaga dentro de você, sustentando sua esperança e força na matéria.',
        'quinta_msg': 'A Quinta Força ativa o Mestre Solar: a consciência iluminada que reconhece o divino em cada ser e vive na paz do Agora.',
    },
}

# Descricao longa de cada tom
TONS_PROFUNDO = {
    1: 'O Raio da Unificação. Atrai a intenção primordial, estabelece o propósito dos 13 dias e conecta a alma à sua meta magnética.',
    2: 'O Raio da Polaridade. Identifica os desafios, reconhece os obstáculos e ancora a estabilidade necessária para não tombar diante dos atritos.',
    3: 'O Raio do Movimento. Ativa a energia do serviço, cria pontes e vínculos entre pessoas e recursos, colocando o propósito em ação dinâmica.',
    4: 'O Raio da Estrutura. Define os parâmetros, mede prioridades e desenha a forma exata e executável que a ideia precisa ter no chão.',
    5: 'O Raio do Comando. Reúne recursos internos e externos, potencializa a força central e estabelece liderança com autoridade radiante.',
    6: 'O Raio do Equilíbrio. Organiza a rotina, equilibra as demandas internas e externas e estabelece igualdade e estabilidade na caminhada.',
    7: 'O Raio da Sintonização. Canaliza a intuição superior, sintoniza o canal receptivo e inspira ações alinhadas com a ordem cósmica.',
    8: 'O Raio da Integridade. Harmoniza a conduta diária com a verdade do coração, modelando através do exemplo prático aquilo em que acredita.',
    9: 'O Raio da Intenção. Dispara a flecha da ação, pulsa a determinação no mundo e mobiliza forças para realizar o propósito na matéria.',
    10: 'O Raio da Manifestação. Produz resultados visíveis, aperfeiçoa os processos e colhe os frutos concretos do trabalho realizado.',
    11: 'O Raio da Liberação. Dissolve bloqueios e rigidezes, solta o controle e desapega do que já cumpriu seu papel para abrir espaço ao novo.',
    12: 'O Raio da Cooperação. Dedica os aprendizados à coletividade, universaliza a sabedoria e expande a cooperação em rede com o todo.',
    13: 'O Raio da Transcendência. Coroa a jornada de 13 passos, integra todos os aprendizados e transcende na presença pura e atemporal.',
}

# Totem xamanico de cada tom: (nome, medicina, ensino)
TOTENS = {
    1: ('Morcego 🦇', 'Navegação no Escuro & Renascimento', 'O Morcego enxerga por ecolocalização no invisível e dorme de cabeça para baixo (nova perspectiva). Ele ensina a soltar velhas identidades para atrair o propósito primordial com coragem.'),
    2: ('Escorpião 🦂', 'Transmutação do Veneno & Defesa Lúcida', 'O Escorpião habita fendas profundas e transmuta a própria toxicidade em medicina protetora. Ele ensina a reconhecer a dualidade e estabilizar os desafios sem medo do atrito.'),
    3: ('Veado 🦌', 'Agilidade Compassiva & Salto Sagrado', 'O Veado pisa com leveza, sensibilidade extrema e rapidez nos saltos. Ele ensina a liderar pelo serviço amoroso, vinculando conexões sinceras sem perder a mansidão.'),
    4: ('Coruja 🦉', 'Visão Noturna Cirúrgica & Estrutura', 'A Coruja gira a cabeça 270 graus e enxerga através de qualquer camuflagem no escuro. Ela ensina a desenhar a forma exata dos projetos e medir prioridades com discernimento.'),
    5: ('Pavão 🦚', 'Irradiação Régia & Maestria de Presença', 'O Pavão abre a cauda de mil olhos dourados sem vergonha de seu esplendor e ingere plantas venenosas sem adoecer. Ele ensina a reunir recursos e comandar com autoridade benevolente.'),
    6: ('Lagarto 🦎', 'Regeneração Somática & Desapego Corporal', 'O Lagarto solta o próprio rabo para escapar de predadores e regenera seu tecido biológico ao sol. Ele ensina a organizar o equilíbrio da rotina soltando pesos sem apego.'),
    7: ('Macaco 🐒', 'Curiosidade Sagrada & Quebra de Rigidez', 'O Macaco salta de galho em galho com inteligência lúdica e desfaz nós complexos brincando. Ele ensina a sintonizar o canal intuitivo quebrando a solenidade pesada do ego.'),
    8: ('Falcão 🦅', 'Voo Altaneiro & Foco Impecável', 'O Falcão sobrevoa as tempestades com visão de raio-X e mergulha em alta velocidade no alvo. Ele ensina a harmonizar a integridade ética, modelando o que se prega na prática.'),
    9: ('Jaguar 🐆', 'Força Silenciosa & Realização da Intenção', 'O Jaguar caminha na floresta sem quebrar um galho e salta no momento exato com precisão letal. Ele ensina a pulsar a intenção no silêncio até materializá-la no mundo físico.'),
    10: ('Cão 🐕', 'Lealdade Instintiva & Amor Protetor', 'O Cão protege o território, serve com devoção desinteressada e fareja perigos à distância. Ele ensina a aperfeiçoar a manifestação material servindo a quem se ama com fidelidade.'),
    11: ('Serpente 🐍', 'Troca de Pele & Kundalini Sagrada', 'A Serpente rasga a própria pele apertada para continuar crescendo e sente as vibrações da Terra pela barriga. Ela ensina a dissolver amarras e libertar o fluxo vital estagnado.'),
    12: ('Coelho 🐇', 'Fertilidade Comunitária & Partilha', 'O Coelho vive em tocas compartilhadas, multiplica recursos e vigia os arredores com atenção mansa. Ele ensina a cooperar em rede e dedicar seus dons à comunidade com generosidade.'),
    13: ('Tartaruga 🐢', 'Paciência Cósmica & Presença Atemporal', 'A Tartaruga carrega o mapa do tempo natural no casco (13 escamas centrais e 28 periféricas). Ela ensina a transcender a pressa ilusória e perseverar na presença do Agora.'),
}
